{{- $createSecret := or (and (not .Values.config.email.existingSecret) (or .Values.config.email.address .Values.config.email.sendgrid)) (and (not .Values.config.documentIntelligence.existingSecret) (or .Values.config.documentIntelligence.endpoint .Values.config.documentIntelligence.key)) -}}
{{- if $createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recipya.fullname" . }}-secrets
  labels:
    {{- include "recipya.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.config.email.existingSecret }}
  {{- if .Values.config.email.address }}
  {{ .Values.config.email.addressKey }}: {{ .Values.config.email.address | b64enc }}
  {{- end }}
  {{- if .Values.config.email.sendgrid }}
  {{ .Values.config.email.sendgridKey }}: {{ .Values.config.email.sendgrid | b64enc }}
  {{- end }}
  {{- end }}
  
  {{- if not .Values.config.documentIntelligence.existingSecret }}
  {{- if .Values.config.documentIntelligence.endpoint }}
  {{ .Values.config.documentIntelligence.endpointKey }}: {{ .Values.config.documentIntelligence.endpoint | b64enc }}
  {{- end }}
  {{- if .Values.config.documentIntelligence.key }}
  {{ .Values.config.documentIntelligence.keyKey }}: {{ .Values.config.documentIntelligence.key | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}