apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recipya.fullname" . }}-secrets
  labels:
    {{- include "recipya.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.config.email.existingSecret }}
  {{ .Values.config.email.addressKey }}: {{ .Values.config.email.address | b64enc }}
  {{ .Values.config.email.sendgridKey }}: {{ .Values.config.email.sendgrid | b64enc }}
  {{- end }}
  
  {{- if not .Values.config.documentIntelligence.existingSecret }}
  {{ .Values.config.documentIntelligence.endpointKey }}: {{ .Values.config.documentIntelligence.endpoint | b64enc }}
  {{ .Values.config.documentIntelligence.keyKey }}: {{ .Values.config.documentIntelligence.key | b64enc }}
  {{- end }}