ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: mealie.tomik.lat
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - mealie.tomik.lat

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 3Gi

postgresql:
  enabled: true
  # External PostgreSQL settings
  external:
    enabled: true
    host: "postgres-cluster-pooler.dbs.svc.cluster.local"
    port: 5432
    database: "mealie"
    user: "mealie_user"
    password: "7OemzeEtwYF1y7FyqRi6"

## Environment variables
env:
  # General Settings
  PUID: "911"
  PGID: "911"
  DEFAULT_GROUP: "Home"
  DEFAULT_HOUSEHOLD: "Family"
  BASE_URL: "http://localhost:9000"
  TOKEN_TIME: "48"
  API_PORT: "9000"
  API_DOCS: "true"
  TZ: "UTC"
  ALLOW_SIGNUP: "false"
  ALLOW_PASSWORD_LOGIN: "true"
  LOG_LEVEL: "info"
  DAILY_SCHEDULE_TIME: "23:45"
  
  # Security
  SECURITY_MAX_LOGIN_ATTEMPTS: "5"
  SECURITY_USER_LOCKOUT_TIME: "24"
  
  # Database
  DB_ENGINE: "postgres"
  
  # Webworker
  UVICORN_WORKERS: "1"