{{- if and .Values.gluetun.enabled .Values.gluetun.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrent-vpn.fullname" . }}-vpn-credentials
  labels:
    {{- include "qbittorrent-vpn.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.gluetun.vpn.type "openvpn" }}
  {{ .Values.gluetun.credentials.usernameKey }}: {{ .Values.gluetun.credentials.username | b64enc | quote }}
  {{ .Values.gluetun.credentials.passwordKey }}: {{ .Values.gluetun.credentials.password | b64enc | quote }}
  {{- end }}
  
  {{- if and (eq .Values.gluetun.vpn.type "wireguard") .Values.gluetun.vpn.wireguard.privateKey }}
  wireguard_private_key: {{ .Values.gluetun.vpn.wireguard.privateKey | b64enc | quote }}
  {{- end }}
{{- end }}