image:
  repository: donetick/donetick
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 2021

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: donetick.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - donetick.example.com

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 1Gi

env:
  - name: DT_ENV
    value: selfhosted
  - name: DT_SQLITE_PATH
    value: /donetick-data/donetick.db  

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

config:
  name: "selfhosted"
  is_done_tick_dot_com: false
  is_user_creation_disabled: false
  telegram:
    token: ""
  pushover:
    token: ""
  database:
    type: "sqlite"
    migration: true
    # these are only required for postgres
    host: "secret"
    port: 5432
    user: "secret"
    password: "secret"
    name: "secret"
  jwt:
    secret: "secret"
    session_time: 168h
    max_refresh: 168h
  server:
    port: 2021
    read_timeout: 10s
    write_timeout: 10s
    rate_period: 60s
    rate_limit: 300
    cors_allow_origins:
      - "http://localhost:5173"
      - "http://localhost:7926"
      # the below are required for the android app to work
      - "https://localhost"
      - "capacitor://localhost"
    serve_frontend: true
  scheduler_jobs:
    due_job: 30m
    overdue_job: 3h
    pre_due_job: 3h
  email:
    host: 
    port: 
    key: 
    email:  
    appHost:  
  oauth2:
    client_id: 
    client_secret: 
    auth_url: 
    token_url: 
    user_info_url: 
    redirect_url: 
    name: 