{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karakeep.secretName" . }}
  labels:
    {{- include "karakeep.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.env }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}