apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "donetick.fullname" . }}-configmap
  labels:
    {{- include "donetick.labels" . | nindent 4 }}
data:
  selfhosted.yaml: |
    name: {{ .Values.config.name | quote }}
    is_done_tick_dot_com: {{ .Values.config.is_done_tick_dot_com }}
    is_user_creation_disabled: {{ .Values.config.is_user_creation_disabled }}
    telegram:
      token: {{ .Values.config.telegram.token | default "" | quote }}
    pushover:
      token: {{ .Values.config.pushover.token | default "" | quote }}
    database:
      type: {{ .Values.config.database.type | default "sqlite" | quote }}
      migration: {{ .Values.config.database.migration }}
      host: {{ .Values.config.database.host | default "secret" | quote }}
      port: {{ .Values.config.database.port | default 5432 }}
      user: {{ .Values.config.database.user | default "secret" | quote }}
      password: {{ .Values.config.database.password | default "secret" | quote }}
      name: {{ .Values.config.database.name | default "secret" | quote }}
    jwt:
      secret: {{ .Values.config.jwt.secret | quote }}
      session_time: {{ .Values.config.jwt.session_time | default "168h" | quote }}
      max_refresh: {{ .Values.config.jwt.max_refresh | default "168h" | quote }}
    server:
      port: {{ .Values.config.server.port | default 2021 }}
      read_timeout: {{ .Values.config.server.read_timeout | default "10s" | quote }}
      write_timeout: {{ .Values.config.server.write_timeout | default "10s" | quote }}
      rate_period: {{ .Values.config.server.rate_period | default "60s" | quote }}
      rate_limit: {{ .Values.config.server.rate_limit | default 300 }}
      cors_allow_origins:
        {{- range .Values.config.server.cors_allow_origins }}
        - {{ . | quote }}
        {{- end }}
      serve_frontend: {{ .Values.config.server.serve_frontend | default true }}
    scheduler_jobs:
      due_job: {{ .Values.config.scheduler_jobs.due_job | default "30m" | quote }}
      overdue_job: {{ .Values.config.scheduler_jobs.overdue_job | default "3h" | quote }}
      pre_due_job: {{ .Values.config.scheduler_jobs.pre_due_job | default "3h" | quote }}
    email:
      host: {{ .Values.config.email.host | quote }}
      port: {{ .Values.config.email.port | quote }}
      key: {{ .Values.config.email.key | quote }}
      email: {{ .Values.config.email.email | quote }}
      appHost: {{ .Values.config.email.appHost | quote }}
    oauth2:
      client_id: {{ .Values.config.oauth2.client_id | quote }}
      client_secret: {{ .Values.config.oauth2.client_secret | quote }}
      auth_url: {{ .Values.config.oauth2.auth_url | quote }}
      token_url: {{ .Values.config.oauth2.token_url | quote }}
      user_info_url: {{ .Values.config.oauth2.user_info_url | quote }}
      redirect_url: {{ .Values.config.oauth2.redirect_url | quote }}
      name: {{ .Values.config.oauth2.name | quote }}