apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "donetick.fullname" . }}
  labels:
    {{- include "donetick.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "donetick.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "donetick.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/donetick-core"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "donetick.fullname" . }}-config
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "donetick.fullname" . }}-data