apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "donetick.fullname" . }}
  labels:
    {{- include "donetick.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "donetick.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "donetick.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/donetick"]
          ports:
            - name: http
              containerPort: 2021
              protocol: TCP
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config          
            - name: data
              mountPath: /donetick-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "donetick.fullname" . }}-configmap
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "donetick.fullname" . }}-data